SELECT

    COUNT(DISTINCT CUSTOMER_ID) AS ACTIVE_CUSTOMERS,

    SUM(MRR) AS TOTAL_MRR,

    SUM(MRR) * 12 AS ARR,

    SUM(EXPANSION_REVENUE) AS EXPANSION_REVENUE,

    SUM(CONTRACTION_REVENUE) AS CONTRACTION_REVENUE,

    SUM(CHURN_FLAG) AS CHURNED_CUSTOMERS,

    ROUND(
        SUM(CHURN_FLAG) * 100.0
        / COUNT(DISTINCT CUSTOMER_ID),
        2
    ) AS CHURN_RATE_PCT

FROM {{ ref('stg_revenue') }}

-- this table answers:
-- ACTIVE_CUSTOMERS
-- TOTAL_MRR
-- ARR
-- EXPANSION_REVENUE
-- CONTRACTION_REVENUE
-- CHURNED_CUSTOMERS
-- CHURN_RATE_PCT